### Get all products
GET http://localhost:8000/products

### Create a new product
POST http://localhost:8000/products

### Get product by id
GET http://localhost:8000/products/1

### Update product by id
PUT http://localhost:8000/products/1

### Delete product by id
DELETE http://localhost:8000/products/1

### Get all orders
GET http://localhost:8000/orders

### Create a new order
POST http://localhost:8000/orders

### Get order by id
GET http://localhost:8000/orders/1


### Delete order by id
DELETE http://localhost:8000/orders/1

###
