### Get all products
GET http://localhost:8000/products

### Create a new product
POST http://localhost:8000/products
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=RestApiBoundary

--RestApiBoundary
Content-Disposition: form/data; name="name"

MacBook Pro
--RestApiBoundary
Content-Disposition: form/data; name="price"

2800
--RestApiBoundary
Content-Disposition: form/data; name="image"; filename="dummy-product.png"
Content-Type: image/png

< dummy-product.png
--RestApiBoundary

### Get product by id
GET http://localhost:8000/products/42

### Update product by id
PUT http://localhost:8000/products/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "MacBook Pro",
    "price": "2900"
}

### Delete product by id
DELETE http://localhost:8000/products/1
Authorization: Bearer {{token}}

### Get all orders
GET http://localhost:8000/orders
Authorization: Bearer {{token}}
Authorization: Bearer {{token}}

### Create a new order
POST http://localhost:8000/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": 2,
    "quantity": 1
}

### Get order by id
GET http://localhost:8000/orders/1
Authorization: Bearer {{token}}

### Delete order by id
DELETE http://localhost:8000/orders/1
Authorization: Bearer {{token}}

### Create a new user
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password" : "secret"
}

### Log in a user
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password" : "secret"
}

> {% client.global.set("token", response.body.token); %}

###

